const constants = {
  ROUTE: {
    HOME_PAGE: "/",
    TOPIC_PAGE: "/topics",
    ARTICLES_PAGE: "/articles",
    CAMPAIGN_PAGE: "/campaign",
    GALLERY_PAGE: "/gallery",
    CAMPAIGN_DETAILS:"/campaigndetails",
    ESSENTIAL: "/essentials",
    PROFILE: "/profile",
    ALL_POSTS: "/allposts",
    ADD_POSTS: "/addposts",
    ADD_CAMPAIGNS: "/addcampaigns",
    ALL_CAMPAIGNS: "/allcampaigns",
    NOTIFICATIONS: "/notifications",
    ACCESSLOG: "/accesslog",
    ALL_ORGANIZATION: "/allorganization",
    ADD_ORGANIZATION: "/addorganization",
    LANDSCAPE_PAGE: "/landscape",
    TOPIC_DETAILS: "/topic-details",
    SEARCH_PAGE: "/search",
    EVENT_PAGE: "/event",
    MEMBER: "/member",
    ACCOUNT:"/account",
    VIDEOLIST:"/video",
    GALLERY_DETAILS: "/gallerydetails",
    FEATUREDLIST: "/featured",
    LANDSCAPE_DETAILS: "/landscapedetail",
    VIDEO_DETAILS: "/videodetails",
    ESSENTIAL_DETAILS: "/essentialdetails",
    ARTICLE_DETAILS: "/articledetails"
  },
};
export default constants;
